const typeList = [
    // movie
    { "type_id": 1, "type_name": "电影" },
    { "type_id": 7, "type_name": "喜剧片" },
    { "type_id": 8, "type_name": "爱情片" },
    { "type_id": 9, "type_name": "科幻片" },
    { "type_id": 10, "type_name": "恐怖片" },
    { "type_id": 11, "type_name": "剧情片" },
    { "type_id": 12, "type_name": "战争片" },
    { "type_id": 6, "type_name": "动作片" },
    { "type_id": 21, "type_name": "悬疑片" },
    { "type_id": 22, "type_name": "犯罪片" },
    { "type_id": 38, "type_name": "冒险片" },
    { "type_id": 40, "type_name": "惊悚片" },
    { "type_id": 43, "type_name": "奇幻片" },
    // soap
    { "type_id": 2, "type_name": "电视剧" },
    { "type_id": 13, "type_name": "国产剧" },
    { "type_id": 14, "type_name": "欧美剧" },
    { "type_id": 15, "type_name": "韩剧" },
    { "type_id": 16, "type_name": "日剧" },
    { "type_id": 17, "type_name": "港剧" },
    { "type_id": 18, "type_name": "台剧" },
    { "type_id": 19, "type_name": "泰剧" },
    { "type_id": 23, "type_name": "海外剧" },
    // zongyi
    { "type_id": 3, "type_name": "综艺" },
    { "type_id": 25, "type_name": "大陆综艺" },
    { "type_id": 26, "type_name": "日韩综艺" },
    { "type_id": 27, "type_name": "港台综艺" },
    { "type_id": 28, "type_name": "欧美综艺" },
    // animation
    { "type_id": 4, "type_name": "动漫" },
    { "type_id": 29, "type_name": "国产动漫" },
    { "type_id": 30, "type_name": "日韩动漫" },
    { "type_id": 31, "type_name": "欧美动漫" },
    { "type_id": 39, "type_name": "动画片" },
    { "type_id": 44, "type_name": "港台动漫" },
    { "type_id": 45, "type_name": "海外动漫" },
    // game
    { "type_id": 20, "type_name": "纪录片" },
    { "type_id": 47, "type_name": "演唱会" },
    { "type_id": 48, "type_name": "体育赛事" },
    { "type_id": 49, "type_name": "篮球" },
    { "type_id": 50, "type_name": "足球" },
    { "type_id": 51, "type_name": "预告片" },
    { "type_id": 52, "type_name": "斯诺克" },
    // spec
    { "type_id": 46, "type_name": "理论片" },
  ]