on:
  push:
    branches:
      - master
  schedule:
    - cron: "6 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Install dependencies
        run: |
          npm install
          npm run update3
      - name: Commit
        run: |
          git config --global user.email githubAction@gmail.com
          git config --global user.name githubAction
          git add .
          git commit -m "action: auto update"
          git pull --rebase
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
